spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5433/JenkinsDb
    username: JenkinsDb
    password: JenkinsDb

  jpa:
    properties:
      hibernate:
        default_schema: public



