spring:



  jpa:
    properties:
      hibernate:
        default_schema: public


  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  docker:
    compose:
      file: src/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only

server:
  port: 8443
  ssl:
    enabled: true
    key-alias: spring-https
    key-store: classpath:java.p12
    key-store-password: password
    key-store-type: PKCS12
    key-password: password